sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

stages:
  - name: release_snapshot
  - name: release_final

jobs:
  include:
 #   - stage: build
 #     script: ./gradlew build -s
    - stage: release_snapshot
      script: ./gradlew build dockerTest dockerPush reckonTagPush -Preckon.scope=patch -Preckon.stage=snapshot
    - stage: release_final
      script: ./gradlew build dockerTest dockerPush reckonTagPush -Preckon.scope=patch -Preckon.stage=final
