sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

stages:
  - name: release_snapshot
  - name: release_final

jobs:
  include:
 #   - stage: build
 #     script: ./gradlew build -s
    - stage: release_snapshot
      deploy:
        provider: script
        script: ./gradlew build dockerTest pushDockerImages reckonTagPush -Preckon.scope=patch -Preckon.stage=snapshot
        on:
          tags: false
    - stage: release_final
      script: ./gradlew build dockerTest pushDockerImages reckonTagPush -Preckon.scope=patch -Preckon.stage=final
      on:
        tags: true