sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

jobs:
include:
  - stage: build
    script: ./gradlew build -s
  - stage: release-snapshot
    script: skip
    deploy:
      provider: script
      script: ./gradlew build dockerTest dockerPush reckonTagPush -Preckon.scope=patch -Preckon.stage=snapshot
      on:
        tags: false
  - stage: release-final
    script: skip
    deploy:
      provider: script
      script: ./gradlew build dockerTest dockerPush reckonTagPush -Preckon.scope=patch -Preckon.stage=final
      on:
        tags: true

