sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true


jobs:
  include:
    - script: ./gradlew build dockerTest dockerPush reckonTagPush -Preckon.scope=patch -Preckon.stage=snapshot
      if: tag = false
    - script: ./gradlew build dockerTest dockerPush reckonTagPush -Preckon.scope=patch -Preckon.stage=final
      if: tag = true
