version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
                
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  build:
    commands:
      - echo Starting build `date`
      - chmod +rx -R *
      - ./gradlew clean build -x test
      - GIT_SHA=`./gradlew -q getVersion`
      - sed -i -e "s/IMAGE_TAG/$GIT_SHA/g" buildspec.yml
      - docker build -t sogis/ilivalidator-web-service:IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push sogis/ilivalidator-web-service:IMAGE_TAG
      - echo Deleting Dockerfile
      - rm Dockerfile
artifacts:
  files:
    - '**/*'
